//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Crm.Accelerator.Cca.Cti.Samples.CtiRoot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Crm.Accelerator.Cca.Cti.Samples.CtiRoot.Properties.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Agent Number : .
        /// </summary>
        public static string AGENT_NUMBER {
            get {
                return ResourceManager.GetString("AGENT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close this session now?.
        /// </summary>
        public static string DESKTOP_CLOSE_AFTER_TRANSFER {
            get {
                return ResourceManager.GetString("DESKTOP_CLOSE_AFTER_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESKTOP_ERR_TRANSFERRING_CALL: Failed to transfer the call.  Please try again..
        /// </summary>
        public static string DESKTOP_ERR_TRANSFERRING_CALL {
            get {
                return ResourceManager.GetString("DESKTOP_ERR_TRANSFERRING_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        public static string SELECT_CALL_DLG_BTN_CANCEL {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        public static string SELECT_CALL_DLG_BTN_OK {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which call to use:.
        /// </summary>
        public static string SELECT_CALL_DLG_LABEL1 {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_LABEL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parties.
        /// </summary>
        public static string SELECT_CALL_DLG_PARTIES_COL {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_PARTIES_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select any row in the list..
        /// </summary>
        public static string SELECT_CALL_DLG_SELECT_A_CALL {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_SELECT_A_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string SELECT_CALL_DLG_STARTED_COL {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_STARTED_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string SELECT_CALL_DLG_STATE_COL {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_STATE_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Call.
        /// </summary>
        public static string SELECT_CALL_DLG_TEXT {
            get {
                return ResourceManager.GetString("SELECT_CALL_DLG_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNABLE TO CONFIGURE PHONE.
        /// </summary>
        public static string UNABLETOCONFIGUREPHONE {
            get {
                return ResourceManager.GetString("UNABLETOCONFIGUREPHONE", resourceCulture);
            }
        }
    }
}
