

using System.Diagnostics.CodeAnalysis;

[module: SuppressMessage("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces", Scope="type", Target="Microsoft.Crm.Accelerator.Cca.Cti.Samples.CtiRoot.CtiRoot", Justification="Maintainability and Design issues are not being targeted for fixing in this release")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="Microsoft.Crm.Accelerator.Cca.Cti.Samples.CtiRoot.CtiRoot.#Unhold(System.Int32)", MessageId="Unhold", Justification="Maintainability and Design issues are not being targeted for fixing in this release")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope="member", Target="Microsoft.Crm.Accelerator.Cca.Cti.Samples.CtiRoot.CtiRoot.#.ctor(System.Guid,System.String,System.String)", MessageId="XML", Justification="Maintainability and Design issues are not being targeted for fixing in this release")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope="member", Target="Microsoft.Crm.Accelerator.Cca.Cti.Samples.CtiRoot.CtiRoot.#.ctor(System.Guid,System.String,System.String)", MessageId="ID", Justification="Maintainability and Design issues are not being targeted for fixing in this release")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="Microsoft.Crm.Accelerator.Cca.Cti.Samples.CtiRoot.CtiRoot.#CanUnhold(System.Int32)", MessageId="Unhold", Justification="Maintainability and Design issues are not being targeted for fixing in this release")]
[module: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope="member", Target="Microsoft.Crm.Accelerator.Cca.Cti.Samples.CtiRoot.CtiRoot.#GetNumberOfCalls()", Justification="Maintainability and Design issues are not being targeted for fixing in this release")]
[module: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope="member", Target="Microsoft.Crm.Accelerator.Cca.Cti.Samples.CtiRoot.CtiRoot.#GetCalls()", Justification="Maintainability and Design issues are not being targeted for fixing in this release")]
[module: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope="member", Target="Microsoft.Crm.Accelerator.Cca.Cti.Samples.CtiRoot.CtiRoot.#GetActiveCall()", Justification="Maintainability and Design issues are not being targeted for fixing in this release")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="type", Target="Microsoft.Crm.Accelerator.Cca.Cti.Samples.CtiRoot.SelectCallDlg", MessageId="Dlg", Justification="Maintainability and Design issues are not being targeted for fixing in this release")]
[module: SuppressMessage("Microsoft.Globalization", "CA9879:AvoidLeadingTrailingSpaceResource", Scope="resource", Target="Microsoft.Crm.Accelerator.Cca.Cti.Samples.CtiRoot.Properties.ResourceStrings.resources", MessageId="AGENT_NUMBER", Justification="Maintainability and Design issues are not being targeted for fixing in this release")]
[module: SuppressMessage("Microsoft.Globalization", "CA9879:AvoidLeadingTrailingSpaceResource", Scope="resource", Target="Microsoft.Crm.Accelerator.Cca.Cti.Samples.CtiRoot.GetAgentId.resources", MessageId="lbAgentId.Text", Justification="Maintainability and Design issues are not being targeted for fixing in this release")]